server.port: 8080
spring:
  application:
    name: intro-to-spring-boot
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always
